version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
- test